<?php

namespace ContainerGZxbAGw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_OUYp96CService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.oUYp96C' shared service.
     *
     * @return \App\Controller\FactureRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\MainController::facture_acte()": the $factureRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\FactureRepository". Did you forget to add a use statement?');
    }
}
