<?php

namespace ContainerGZxbAGw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QAM6fn_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QAM6fn.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QAM6fn.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'factureRepository' => ['privates', '.errored.oUYp96C', NULL, 'Cannot determine controller argument for "App\\Controller\\MainController::facture_acte()": the $factureRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\FactureRepository". Did you forget to add a use statement?'],
        ], [
            'factureRepository' => '?',
        ]);
    }
}
