<?php

namespace Container8vG374F;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KR1hhmIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kR1hhmI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kR1hhmI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'acte' => ['privates', '.errored..service_locator.kR1hhmI.App\\Entity\\Acte', NULL, 'Cannot autowire service ".service_locator.kR1hhmI": it references class "App\\Entity\\Acte" but no such service exists.'],
        ], [
            'acte' => 'App\\Entity\\Acte',
        ]);
    }
}
