<?php

namespace Container8vG374F;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Mk9shxUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mk9shxU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mk9shxU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'patient' => ['privates', '.errored..service_locator.mk9shxU.App\\Entity\\Patient', NULL, 'Cannot autowire service ".service_locator.mk9shxU": it references class "App\\Entity\\Patient" but no such service exists.'],
        ], [
            'patient' => 'App\\Entity\\Patient',
        ]);
    }
}
