<?php

namespace Container8vG374F;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.kR1hhmI.App\Entity\Acte' shared service.
     *
     * @return \App\Entity\Acte
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.kR1hhmI": it references class "App\\Entity\\Acte" but no such service exists.');
    }
}
