<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXyFYoWj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXyFYoWj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXyFYoWj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXyFYoWj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXyFYoWj\App_KernelDevDebugContainer([
    'container.build_hash' => 'XyFYoWj',
    'container.build_id' => '7ce3534b',
    'container.build_time' => 1618817359,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXyFYoWj');
