<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGZxbAGw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGZxbAGw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGZxbAGw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGZxbAGw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGZxbAGw\App_KernelDevDebugContainer([
    'container.build_hash' => 'GZxbAGw',
    'container.build_id' => '14a2c02e',
    'container.build_time' => 1617115801,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGZxbAGw');
