<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFgneQwc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFgneQwc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFgneQwc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFgneQwc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFgneQwc\App_KernelDevDebugContainer([
    'container.build_hash' => 'FgneQwc',
    'container.build_id' => 'd47e1c3a',
    'container.build_time' => 1618214004,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFgneQwc');
